<?php
return array(
    'DATABASE_DEFAULT' => FIXME,    // e.g. 'mysql',    'pgsql',    ...
    'DATABASE_NAME' => FIXME,       // e.g. 'geogebra', 'forge',    ...
    'DATABASE_USER' => FIXME,       // e.g. 'nbusr',    'postgres', ...
    'DATABASE_PASSWORD' => FIXME,   // e.g. 'nbusr123', 'abcdef',   ...
    'ROUTES_PREFIX' => FIXME,       // e.g. '', 'geogebra',   ...
);
