---

- name: Apache | Install
  apt: pkg=apache2 state=present

- name: Apache | Enable rewrite module
  command: a2enmod rewrite creates=/etc/apache2/mods-enabled/rewrite.load
  notify:
    - Restart Apache2

- name: Apache | Replace envvars
  template: src=apache-envvars.j2
            dest=/etc/apache2/envvars
            owner=apache
            group=apache
            mode=0644

- name: Apache | remove default config file
  file: dest=/etc/apache2/sites-enabled/000-default.conf
        state=absent

- name: Apache | Ensure running state
  service: name=apache2 state=started

- name: PHP5 | install with modules
  apt: name={{ item }} state=present
  with_items:
    - php5
    - php5-mcrypt
    - php5-json
    - php5-cli
    - php5-pgsql

- name: PHP5 | php5enmod mcrypt (dont know what is this)
  shell: php5enmod mcrypt
  notify:
    - Restart Apache2
